### ISSUE TITLE
fix: startDate needs to be Date.Now() after login

### ISSUE THREAD

**Issue by daborton** [brown-ccv/neuro-task-starter#128] opened 2022-11-19 04:30 UTC
Currently, startDate refers to the app window creation, not the start of the experiment, which can be a very different time. Further, time_elapsed from jsPsych is relative to the start of the experiment, not the creation of the app window. This is problematic when synchronizing to other data collected in parallel to the task data.

**Comment by RobertGemmaJr** [comment] 2023-02-14 16:50
Duplicate of #126

**Closed as completed** 2023-03-17 19:56 UTC
Labels: bug
